### ISSUE TITLE
Please update Flutter downloader at pub.dartlang.org

### ISSUE THREAD

**Issue by shubham9543** [hnvn/flutter_downloader#15]
https://pub.dartlang.org/packages/flutter_downloader#-versions-tab-

the version available here doesn't contain major changes present in readme.md. 
like DownloadTask class doesn't contain these members like savedDir, url.
 please update the plugin there.

**Comment by cbenhagen** [comment]
What you see in the current master is a big update (thanks a lot @hnvn!) which is almost finished but not yet as polished as it needs to be to be submitted to pub.

If you want to live on the bleeding edge, nothing stops you from putting this in your `pubspec.yaml`:
```yaml
dependencies:
  flutter_downloader:
    git: https://github.com/hnvn/flutter_downloader.git
```
